chrisleekr/binance-trading-bot

public/index.html
Hello, great work !
I tried running it behind a proxy, which was checking that the user was correctly authenticated.
Unfortunately, only the `site.webmanifest` file was not loading properly. I found that in order for the browser to attach the credentials to the request when requesting the file, the link markup should contain `crossorigin="use-credentials"` and this `even if the manifest file is in the same origin as the current page.` (quote from documentation below)
With this parameters, it worked.
More informations [https://developer.mozilla.org/en-US/docs/Web/Manifest](https://developer.mozilla.org/en-US/docs/Web/Manifest)
=> Allow usage behind a protected reverse proxy

README.md, app/helpers/__tests__/mongo.test.js, app/helpers/mongo.js, app/jobs/trailingTrade/__tests__/configuration.test.js, app/jobs/trailingTrade/configuration.js, app/jobs/trailingTrade/step/__tests__/get-indicators.test.js, app/jobs/trailingTrade/step/__tests__/place-buy-order.test.js, app/jobs/trailingTrade/step/__tests__/place-sell-order.test.js, app/jobs/trailingTrade/step/get-indicators.js, app/jobs/trailingTrade/step/place-buy-order.js, app/jobs/trailingTrade/step/place-sell-order.js, app/jobs/trailingTrade/symbol.js, app/websocket/__tests__/configure.test.js, app/websocket/configure.js, app/websocket/handlers/__tests__/fixtures/latest-stats.json, app/websocket/handlers/__tests__/index.test.js, app/websocket/handlers/__tests__/latest.test.js, app/websocket/handlers/__tests__/setting-update.test.js, app/websocket/handlers/__tests__/symbol-setting-delete.test.js, app/websocket/handlers/index.js, app/websocket/handlers/latest.js, app/websocket/handlers/setting-update.js, app/websocket/handlers/symbol-setting-delete.js, jest.setup.js, package.json, public/index.html, public/js/App.js, public/js/HighlightChange.js, public/js/SettingIcon.js, public/js/SymbolSettingIcon.js
There were several reports that the configuration is not working as expected. And found the code had a typo.
https://github.com/chrisleekr/binance-trading-bot/issues/57
https://github.com/chrisleekr/binance-trading-bot/issues/54
https://github.com/chrisleekr/binance-trading-bot/issues/52
Tested with the Binance test server in my local development environment.
=> Bug fix with configuration

package.json, scripts/docker-build.ps1
Added a new npm task for building the docker image under Windows using PowerShell. To run,
```
npm run docker:build:win
```
By default it will do the `production` build, to use `development` build, run:
```
npm run docker:build:win -- -env dev
```
#77
I checked the built image with `docker inspect`:
```
npm run docker:build:win
```
```
npm run docker:build:win -- -env dev
```
=> Add npm task for building docker image on Windows

app/cronjob/trailingTrade/step/__tests__/ensure-manual-buy-order.test.js, app/cronjob/trailingTrade/step/ensure-manual-buy-order.js
The bot sends unexpected messages to Slack when the API didn't return the order because API is busy.
This PR is fixing the step `ensure-manual-buy-order.js` to not throw an error when the order was not found. The order must be found if the order was successfully placed.
#100
=> bug: Fixed order not found issue

public/index.html, public/js/CoinWrapperBuySignal.js, public/js/CoinWrapperSetting.js, public/js/ManualTradeIcon.js, public/js/SymbolManualTradeIcon.js
Just a small enhancement for the UI to show a badge when a symbol configuration is customised. It was added by @chrisleekr but it is removed in current releases while developing the bot and we are just bringing it back.
#170 
Sometimes we don't know which symbol is customised and which is not. This feature solves the issue.
| Customised Symbol | Not Customised Symbol |
| ---------------------- | -------------------------- |
| ![image](https://user-images.githubusercontent.com/31035020/127746742-3d90d184-3a0f-4d1e-89f9-644271342f7c.png) | ![image](https://user-images.githubusercontent.com/31035020/127746760-4b727bb9-882d-453d-8d7f-216775ebaf56.png) |
=> feat: Show badge for the customised symbol configuration

CHANGELOG.md, app/cronjob/trailingTradeIndicator/step/__tests__/get-closed-trades.test.js, app/cronjob/trailingTradeIndicator/step/get-closed-trades.js, app/frontend/webserver/handlers/__tests__/closed-trades-set-period.test.js, app/frontend/webserver/handlers/__tests__/grid-trade-archive-get.test.js, app/frontend/webserver/handlers/closed-trades-set-period.js, app/frontend/webserver/handlers/grid-trade-archive-get.js
- Fixed closed trade history error `can't $divide by zero`. Thanks [@BramFr](https://github.com/BramFr) - [#276](https://github.com/chrisleekr/binance-trading-bot/issues/276)
- Clear closed trade history cache when change the period
#276
=> fix: closed trade query

app/helpers/cache.js, config/custom-environment-variables.json, config/default.json
Introducing new env param "BINANCE_REDIS_DB", this allows the defining of which "db" will be used in Redis Instance.
#286 
Currently, to run multiple bots in one machine, we also need multiple Redis container. However, the Redis Instance itself has multiple DB which can be utilized by each different bot. This means that we can run multiple bots in only one Redis container by defining which DB should the bot use. 
Tested in my RPi.
=> feat: it allows the defining of Redis "db"

CHANGELOG.md, README.ko.md, README.md, README.zh-cn.md, app/__tests__/server-frontend.test.js, app/frontend/webserver/__tests__/configure.test.js, app/frontend/webserver/configure.js, app/frontend/webserver/handlers/__tests__/auth.test.js, app/frontend/webserver/handlers/__tests__/index.test.js, app/frontend/webserver/handlers/auth.js, app/frontend/webserver/handlers/index.js, app/frontend/websocket/__tests__/configure.test.js, app/frontend/websocket/configure.js, app/helpers/cache.js, app/server-frontend.js, config/custom-environment-variables.json, config/default.json, package-lock.json, package.json
This PR will allow the bot to prevent brute force attacks for login. 
It will utilise the rate limit requests for consecutive login failures. 
The rate limit will prevent the user requests once the user failed configured amount of login failures. 
The issue was raised by @caebwallace. Initially, it was suggested using fail2ban. However, it is now alternatively to use the rate limiter inside of the bot due to there are Windows users who do not have fail2ban in the system.
The rate limiter can be configured using the environment parameters.
#293 #281 
To remove the block, go to Redis and remove the login key.
```bash
$ docker exec -it binance-redis /bin/bash
$ redis-cli
> AUTH <redis password>
> KEYS *
> DEL login:::ffff:<IP address>
```
Tested in my server. 
Test code has been written. …
=> feat(auth): support rate limiter to prevent brute force

public/js/AccountWrapper.js, public/js/App.js
Added estimates for quote handled by bot in the Account Balance tab, similar to Issue #303, but for every coin pair handled by the bot currently.
It recycles estimates shown in the frontend cards and simply sums it up in the title.
It supports not only USDT, but all pairs currently analyzed by the bot at the current time.
It has been tested on both the dev and production APIs.
@sentientmachin3
=> feat: added estimates for quote handled by bot

CHANGELOG.md, package-lock.json, public/css/App.css, public/js/AccountWrapper.js, public/js/App.js, public/js/ProfitLossWrapper.js
Moved estimates label to open trades, follows #305
=> refactor: moved estimates label to open trades

.gitlab-ci.yml, .prettierrc.js, CHANGELOG.md, app/cronjob/trailingTrade/step/determine-action.js, app/cronjob/trailingTrade/step/place-buy-order.js, app/cronjob/trailingTradeIndicator/step/__tests__/get-trading-view.test.js, app/cronjob/trailingTradeIndicator/step/get-trading-view.js, docker-compose.yml, package-lock.json, package.json, tradingview/main.py, tradingview/requirements.txt
In this PR, the way to retrieve TradingView technical analysis has been enhanced.
Previously, it was retrieving a single symbol TradingView technical analysis per tick.
Now it will retrieve all symbol's TradingView technical analysis per tick.
=> feat: enhanced tradingview

public/js/SettingIconLastBuyPriceRemoveThreshold.js, public/js/SymbolSettingIcon.js
@Rayn0r has reported XRPBTC/SHIBBUSD are removing the coin due to the last buy removal threshold cannot be set under the minimum notional.
This PR is rectifying the issue.
#372
=> fix: update last buy removal threshold min/step

CHANGELOG.md, docker-compose.rpi.yml, docker-compose.server.yml, docker-compose.yml, tradingview/main.py
This will allow to configure the logging level of the tradingview container by passing an environment variable "TRADINGVIEW_LOG_LEVEL". the accepted values for log level can be viewed here: https://docs.python.org/3/howto/logging.html#logging-levels
#435 
To be able to configure the logging level of tradingview
Tested in my local machine
=> feat: tradingview logging level configuration

public/css/App.css, public/js/App.js, public/js/CoinWrapperAction.js, public/js/CoinWrapperBuySignal.js, public/js/CoinWrapperSellSignal.js, public/js/QuoteAssetGridTradeArchiveIcon.js, public/js/SymbolGridTradeArchiveIcon.js, public/js/SymbolLogsIcon.js
- Fix pagination is showing more pages than actually used and is not compliant with standard pagination methods.
- Add support to show up to all 12 columns on ultra wide monitors.
- Unexecuted grid trades compacted in lists with more than 10 items.
- Object for pagination consistent across the application.
- Fix unnecessary text wrapping if there is enough space to print a text.
- Show Action time in local time.
- Changed time format for logs to 24 hours to be consistent within application.
#437, #440, #442, #444, #446
The fix will improve the user experience.
Tested on UHD display and on wide multi monitor setup with tens of grid trades in various states.
Buttons are visible for available pages only:
Ultra wide monitor support:
Compact grid trade list:
Pagination object at top and bottom …
=> fix: ui improvements

CHANGELOG.md, app/cronjob/trailingTrade/step/__tests__/determine-action.test.js, app/cronjob/trailingTrade/step/determine-action.js, app/cronjob/trailingTrade/step/ensure-grid-trade-order-executed.js, app/cronjob/trailingTrade/step/ensure-manual-order.js, app/cronjob/trailingTrade/step/get-balances.js, app/cronjob/trailingTrade/step/get-override-action.js, app/cronjob/trailingTrade/step/handle-open-orders.js, app/cronjob/trailingTrade/step/place-buy-order.js, app/cronjob/trailingTrade/step/remove-last-buy-price.js, app/cronjob/trailingTradeHelper/configuration.js, app/cronjob/trailingTradeIndicator/step/__tests__/get-closed-trades.test.js, app/cronjob/trailingTradeIndicator/step/get-closed-trades.js, app/frontend/webserver/handlers/closed-trades-set-period.js, app/frontend/websocket/handlers/cancel-order.js, app/frontend/websocket/handlers/dust-transfer-execute.js, app/frontend/websocket/handlers/manual-trade-all-symbols.js, app/frontend/websocket/handlers/manual-trade.js, app/frontend/websocket/handlers/symbol-trigger-buy.js, app/frontend/websocket/handlers/symbol-trigger-sell.js, app/helpers/logger.js, app/server-binance.js, public/index.html, public/index.prod.html, public/js/CoinWrapperAction.js, public/js/ProfitLossWrapper.js, public/js/QuoteAssetGridTradeArchiveIcon.js, public/js/SymbolGridTradeArchiveIcon.js
- Fix data inconsistencies caused by using various timezone settings on client and server side. On the server side dates will be always stored in UTC format regardless of docker container timezone.
- Fix wrong periods of time reported on client in client's timezone is other than UTC. Client will report it's timezone to server to get proper range of data from database based on local timezone.
- Fix wrong first day of week reported on client with locale set to other day than sunday. Client will report it's locale to server to get proper range of data from database based on the locale.
#449
Closed trades were reporting different values on different places in application when day, week or month were selected as reported period of time.
Docker container is using UTC time in default settings …
=> fix: closed trades timezone consistency

app/__tests__/server.test.js, app/binance/__tests__/user.test.js, app/binance/user.js, app/cronjob/__tests__/trailingTrade.test.js, app/cronjob/trailingTrade.js, app/cronjob/trailingTrade/step/ensure-grid-trade-order-executed.js, app/cronjob/trailingTrade/step/get-indicators.js, app/cronjob/trailingTrade/step/handle-open-orders.js, app/server.js, package-lock.json, public/js/SymbolLogsIcon.js
After receiving the order status via WebSocket, the trailing trade process was not executed unless the tick is received.
However, the symbol should be processed after the order status is updated to determine what to do with the updated order.
#451
=> fix: order status update

app/__tests__/server-binance.test.js, app/server-binance.js
When customizing a setting for a specific symbol, it will trigger the `reset-symbol-websockets` channel but unfortunately with an incorrect symbol which will cause the other stuff not to work as expected.
This PR is solving this issue by getting the symbol correctly to do the reset stuff.
- Write tests
- Customizing a setting for a specific symbol will call `reset-symbol-websockets` correctly.
=> fix: incorrect symbol in reset-symbol-websockets

app/cronjob/trailingTrade/step/__tests__/cancel-order.test.js, app/cronjob/trailingTrade/step/cancel-order.js, app/cronjob/trailingTradeHelper/__tests__/common.test.js, app/cronjob/trailingTradeHelper/common.js, app/cronjob/trailingTradeIndicator/step/__tests__/get-closed-trades.test.js, app/cronjob/trailingTradeIndicator/step/get-closed-trades.js, app/frontend/websocket/handlers/__tests__/cancel-order.test.js, app/frontend/websocket/handlers/cancel-order.js, public/css/App.css, public/js/AccountWrapper.js, public/js/AccountWrapperAsset.js, public/js/App.js, public/js/CoinWrapperAction.js, public/js/CoinWrapperBuySignal.js, public/js/CoinWrapperSellSignal.js, public/js/CoinWrapperTradingView.js, public/js/ProfitLossWrapper.js, public/js/QuoteAssetGridTradeArchiveIcon.js, public/js/SymbolGridTradeArchiveIcon.js
- Closed Trades reports in more compact form allowing 20 rows per page.
- Colorized notifications - info = blue, warning = orange, buy = green, sell = red.
- Longer time to show notifications for better readability.
- Improved texts in notifications to differentiate buy and sell notifications.
- Balances not used by the bot are in grey color, balances of quote assets are in orange color.
- In Open Trades indicator added invested ratio and value of portfolio. Quote asset value in Open trades displayed in green color when less than 50% of portfolio is invested, in orange color when less than 90% of portfolio is invested and in red color when more than 90% of portfolio is invested.
- In Closed Trades indicator added last closed trade info.
- Warnings for symbols united in orange color on …
=> feat: improve UI

app/cronjob/trailingTrade/step/__tests__/remove-last-buy-price.test.js, app/cronjob/trailingTrade/step/remove-last-buy-price.js
In a very rare situation, there is a case that it does not archive the order even if all sell orders are executed.
i.e. 
- buy/sell orders are concurrently opened, 
- and then the sell order is executed, but the buy order is still opened. 
- then the `remove-last-buy-price` will not archive the order even after the sell order is executed. 
If all sell orders are executed, then there is no way to sell the remaining coins. 
So it should archive if all sell orders are executed.
N/A
See description
=> fix: archive grid order if all sell orders are executed

app/cronjob/trailingTrade/step/__tests__/remove-last-buy-price.test.js, app/cronjob/trailingTrade/step/remove-last-buy-price.js
When there is an open buy order after all sell orders are executed, then the `remove-last-buy-price` step is not executed because the action is `buy-order-wait`.
However, the step has been updated to archive the grid trade even if there is an open buy order.
This PR is to fix for processing the `remove-last-buy-price` even if the action is `buy-order-wait`.
=> fix: remove last buy price not to check action buy-order-wait

app/binance/__tests__/user.test.js, app/binance/user.js, app/cronjob/trailingTrade/step/__tests__/ensure-grid-trade-order-executed.test.js, app/cronjob/trailingTrade/step/ensure-grid-trade-order-executed.js
This PR is to fix the issue #494 
#494 
Refer #494 
A test case is written and running on my development server.
=> fix: handle execution report

app/cronjob/trailingTradeHelper/__tests__/common.test.js, app/cronjob/trailingTradeHelper/common.js
This PR is going to fix the #491 issue.
We were assigning big numbers for nullable fields when sorting our monitoring symbols such as `Sell - Profit` which makes the sorting in Mongo DB unstable.
Based on that, we rely on `$symbol` field instead of big numbers when the fields are null to make the sorting functionality work as expected.
#491 
Tests have been written to verify that.
Refer to #491
=> fix: sorting symbols when the field is null

app/cronjob/trailingTrade/step/__tests__/cancel-order.test.js, app/cronjob/trailingTrade/step/__tests__/handle-open-orders.test.js, app/cronjob/trailingTrade/step/__tests__/place-buy-order.test.js, app/cronjob/trailingTrade/step/__tests__/place-manual-trade.test.js, app/cronjob/trailingTrade/step/__tests__/place-sell-order.test.js, app/cronjob/trailingTrade/step/__tests__/place-sell-stop-loss-order.test.js, app/cronjob/trailingTrade/step/cancel-order.js, app/cronjob/trailingTrade/step/handle-open-orders.js, app/cronjob/trailingTrade/step/place-buy-order.js, app/cronjob/trailingTrade/step/place-manual-trade.js, app/cronjob/trailingTrade/step/place-sell-order.js, app/cronjob/trailingTrade/step/place-sell-stop-loss-order.js, app/cronjob/trailingTradeHelper/__tests__/common.test.js, app/cronjob/trailingTradeHelper/common.js
When we use `updateAccountInfo` to update the account balances on actions like buy order or sell order, it causes a race condition with the WebSocket because of manually subtracting and adding values.
To solve this, I replaced `updateAccountInfo` with `getAccountFromAPI` on buy order, sell order, and manual orders
Also, I replaced `getAccountInfo` with `getAccountFromAPI` to avoid the race condition too.
#512 
Tests provided
=> fix: account balance calculation

public/index.html, public/index.prod.html
Axios `v1.0` was released 2 days ago and it has some breaking changes.
The CDN url of `axios` in `index.html` and `index.prod.html` always points to the latest version which is dangerous.
Also, it's making the frontend unreachable.
This PR specifies the version of Axios to be always `v0.27.2` 
#520
=> fix: assign specific version for axios

app/helpers/__tests__/cache.test.js, app/helpers/cache.js
`redlock` does not have enough time to unlock after doing the requested operation.
What I mean is that if the `redlock` locks a key for `500ms` and it is expired before calling `lock.unlock()`, and then calling  `lock.unlock()` will throw an exception like:
> Unable to fully release the lock on resource "redlock:trailing-trade-configurations:global"
Because the lock already expired and unlock cannot be done on an expired lock.
Increasing the lock time to `1000ms` solves the problem and it will not affect the performance or the behavior.
Suggestions from: https://github.com/mike-marcacci/node-redlock/issues/65
Partially solve #519 
Tests provided
Posted on #519
=> fix: give redlock enough time for locking

app/cronjob/trailingTrade/step/__tests__/place-buy-order.test.js, app/cronjob/trailingTrade/step/place-buy-order.js, app/cronjob/trailingTradeHelper/__tests__/common.test.js, app/cronjob/trailingTradeHelper/common.js
The existing slack notification settings are still quite verbose even when notifyOrderConfirm and notifyDebug are disabled. Also as a user, if I only enable notifyOrderExecute, I expect to not receive trailing price update notifications. 
This PR tries to address [#515](https://github.com/chrisleekr/binance-trading-bot/issues/515)
This has been tested in live mode on my own setup and trailing updates are not sent anymore with notifyOrderConfirm and notifyDebug set to false.
=> Remove last buy price slack updates unless notifyDebug or notifyOrder are enabled

public/js/CoinWrapperTradingView.js
The existing Tradingview link in the coin wrapper view opens the browser to the Technical Analysis summary. If I want to access the advanced chart instead, I have to do it from TV TA page.
Ideally the coin wrapper view should offer both options:
- access to TV TA page
- access to TV advanced chart
Here is an example of proposed UI:
=> feat: add advanced chart link to Tradingview section

app/cronjob/trailingTradeHelper/__tests__/common.test.js, app/cronjob/trailingTradeHelper/common.js, app/frontend/websocket/handlers/__tests__/fixtures/latest-stats-authenticated.json, app/frontend/websocket/handlers/__tests__/fixtures/latest-stats-not-authenticated-unlock-list.json, app/frontend/websocket/handlers/__tests__/latest.test.js, app/frontend/websocket/handlers/latest.js, public/js/App.js, public/js/Status.js
Let's say we are monitoring **5** symbols and we add one more symbol to our **Global Settings**.
The bot will cache it to `trailing-trade-cache` collection in our Mongo DB as usual and this symbol will show up in the frontend as expected.
- Symbols in Global Settings: 6
- Symbols cached in DB: 6
However, when we remove that symbol from the **Global Settings**, the symbols count will be different than the cached symbols in our database.
- Symbols in Global Settings: 5
- Symbols cached in DB: 6
This is still expected but the pagination will have an issue when we reached like:
- Symbols in Global Settings: 12
- Symbols cached in DB: 13
Hence, we can see only the first 12 symbols from the frontend and we will not be able to see the symbol number 13 because we were paginating our symbols based …
=> fix: symbols pagination #506

public/js/CoinWrapperBuySignal.js, public/js/CoinWrapperSellSignal.js
Improve the frontend with information about the recent orders that took place in the current grid trading.
Today there is no way to get the details of buy and sell orders that the bot executed in a specific coin grid. This PR is about showing the date, price, quantity and amount for each buy/sell order happening in an active trading grid.
This PR simply expands the grid trade sections with order details ( date, price, quantity, amount) only when the grid got executed. This has been tested on my local setup with multi-grid coins.
I couldn't write tests as I couldn't find existing tests dealing with UI aspects that I could reuse.
=> feat: show buy/sell order details in the grid trade sections

public/js/CoinWrapperBuySignal.js
The feature suggests the amount of money you would need to invest in a coin (as a new grid item or a manual trade) to expect closing the grid at break-event (i.e. without losing money) if the coin price eventually reaches your current sell percentage trigger. 
The amount appears only for coins with active grid trades that have one selling grid.
The calculation is based on the following formula: 
**next best grid quantity** = - qi * (1+(p - pi) / (gain * p)), 
where gain = (triggerSellPercentage - 1)
and:
| **Current grid state** | **Suggested best trade**       |
|------------------------|---------------------------|
| Quantity bought (qi)   | Quantity to determine (q) |
| Last price (pi)        | Current price (p)         |
| Spent amount (ai)      | Amount to spend (a)       |
When a …
=> feat: show next best grid amount

CHANGELOG.md, Gruntfile.js, app/frontend/websocket/handlers/__tests__/fixtures/latest-stats-invalid-cache.json, app/frontend/websocket/handlers/__tests__/latest.test.js, app/frontend/websocket/handlers/latest.js, public/index.html, public/js/APIError.js, public/js/App.js
There have been several issues opened that the bot is stuck at loading. 99% of this issue is caused by using a wrong API key. 
To provide more information, I've updated the front end to display an error message when the bot can't get account information.
#538 
As description.
=> feat: show error when use wrong API key

public/js/App.js, public/js/FilterIcon.js, public/js/OrderStats.js
The feature allows the user to hide coins for which buy and sell tradings have been disabled, removing the clutter from the  dashboard.
When I manage many coins, I often struggle to easily access active coins in the dashboard despite the existing sorting options. Hiding disabled coins is a way to improve the usability. This PR extends the `selectedSortOption` object with a new  `hideInactive` attribute.
2 UX features have been implemented:
- Hide inactive trades checkbox in the Sorting popup (FilterIcons.js)
- Add a label in the trading status bar (App.js) to remind inactive coins are hidden
It is working on my setup.
=> feat: hide temporarily disabled trading coins from the dashboard

public/js/CoinWrapperBuySignal.js
I came across an unforeseen grid situation that breaks the calculator introduced in PR #554. 
In the example below, the grid got partially executed, leaving the symbolConfiguration to an undefined `symbolConfiguration.sell.gridTrade`. 
This bug fix hides the calculator for partially executed sell grids.
Running on my production server.
=> fix: hide calculator for partially executed sells

public/js/App.js
Before this PR, if we click on the 🔒 icon on the top right of the screen, the API error page will be shown instead of the lock screen even If I have the correct API credentials.
To solve this, I only give the condition of the lock screen more priority than the API error page. 
The rest changes only for linting.
Not applicable.
Manually clicking on the 🔒 icon will redirect you to the lock screen instead of the condition of API error page
Not applicable.
=> fix: api error page

public/js/CoinWrapperBuySignal.js
The suggested breakeven section of PR #554 is not shown if the buy grid is completed. This PR properly handles the distinction between manual trades (that are currently not supported by the next-buy-grid feature) and buy grids that have all grid trades completed.
Issue detected on my production server and fix now working.
Exemple of grid state that would be missing the breakeven section if this fix is not applied:
=> fix: next-buy-grid missing for completed buy grids

.gitignore, CHANGELOG.md, app/__tests__/server-frontend.test.js, app/frontend/webserver/handlers/__tests__/grid-trade-logs-export.test.js, app/frontend/webserver/handlers/grid-trade-logs-export.js, app/server-frontend.js, nodemon.json, public/js/SymbolLogsIcon.js
This fix is to make log files to be downloaded directly from the web server rather than using `blob`.
#537 
If the log file is enormous, the export function throws an `Invalid string length` error.
To avoid the error, create the log file in the public folder and download it directly from the web server.
To avoid out of the disk space, it will only keep the last 10 log files.
=> fix: download log file directly

CHANGELOG.md, app/cronjob/trailingTradeHelper/__tests__/common.test.js, app/cronjob/trailingTradeHelper/common.js
Fix sorting of symbols to put open trades at the beginning of list. After #496 open trades were at the end of list when descending order is selected which broke previous correct behavior.
#491
=> fix: sorting symbols open trades first

CHANGELOG.md, app/__tests__/server-frontend.test.js, app/frontend/webserver/handlers/__tests__/grid-trade-logs-export.test.js, app/frontend/webserver/handlers/grid-trade-logs-export.js, app/server-frontend.js, app/server.js
=> fix: export logs error

CHANGELOG.md, public/js/ProfitLossWrapper.js
Dust is counted to see real value of asset even if no trade is open.
#570 
There was inconsistency in value of asset between no open trades and when open trades exists.
Tested by checking value when no trade is open comparing with value when there are open trades.
=> fix: open trades more accurate asset indicator

CHANGELOG.md, app/cronjob/trailingTrade/step/__tests__/handle-open-orders.test.js, app/cronjob/trailingTrade/step/handle-open-orders.js
Cancel order when current price is over order price.
#566 
Sometimes the market is very volatile which can cause while buy order is put the price will raise so much the buy order is not executed and stay there until price is dropped again. This is bad because sell order can't be processed while buy order is active and you can miss opportunity to sell.
Same thing with sell order when market drop rapidly and sell order is not executed then you can miss opportunity to buy low or even to trigger stop-loss because you can't sell when anothern sell order is active.
Test provided in __tests__.
=> fix: cancel orders when current price is over order price

app/cronjob/trailingTradeHelper/queue.js
Fix regression in queue init. Queue have to be initialized once only to prevent unexpected result of resetting queue counters while existing queue is still running.
Issue mentioned in #562.
Urgent patch before new version is released.
Passed the tests.
=> fix: regression in queue init

CHANGELOG.md, app/cronjob/trailingTrade/step/__tests__/determine-action.test.js, app/cronjob/trailingTrade/step/__tests__/handle-open-orders.test.js, app/cronjob/trailingTrade/step/determine-action.js, app/cronjob/trailingTrade/step/handle-open-orders.js, public/js/QuoteAssetGridTradeArchiveIcon.js, public/js/SymbolGridTradeArchiveIcon.js
- Stop-loss is higher priority than buy order.
- Added stop-loss highlighting in closed trades.
- It will still allow to finish already opened buy order before stop-loss is triggered to check if stop-loss is unavoidable.
#424
I was highly motivated when it lost -0.77% with stop-loss set to -0.1% (Max loss percentage 0.999). It was much higher overshoot than what I'm able to accept as tolerable margin of error. It should not overshoot even on so tight percentages.
Validated by tests but also in production.
=> fix: stop loss with highest priority

public/js/CoinWrapperBuySignal.js, public/js/SymbolGridCalculator.js
Small improvements on the grid calculator introduced in PR #554:
- The equivalent market prices are now shown both for the rebound and buy trigger percentages
- The calculator is now accessible as long as there is a first buy grid executed. None valid recommendations are rendered as `N/A `
The first enhancement is in response to @peweb [request](https://github.com/chrisleekr/binance-trading-bot/pull/554#issuecomment-1385075405)
This is working on my production server.
**Equivalent prices:**
**N/A indicator:**
=> feat: price equivalents in breakeven calculator

CHANGELOG.md, app/cronjob/trailingTradeIndicator/step/get-trading-view.js, config/custom-environment-variables.json, config/default.json, docker-compose.yml, tradingview/main.py
The existing docker configuration allows to use custom host and port settings for the mongo and redis servers. This PR adds `TRADINGVIEW_HOST` and `TRADINGVIEW_PORT` settings to allow running the tradingview server on a configurable port (instead of the existing hardcoded 8080 port).
This PR doesn't contain the updated image.
=> chore: add docker host and port configurability of tradingview server

CHANGELOG.md, config/custom-environment-variables.json, docker-compose.rpi.yml, docker-compose.server.yml, docker-compose.yml, tradingview/main.py
In the last release, new env params are added to allow setting trading view configurations. And there was an existing env param that was not following the naming conventions. 
However, some env params conflict with the environment parameter in Kubernetes if the service name is ‘tradingview’, which is common to set.
It's good practice to follow previous naming conventions. In addition, prevent clashes by adding prefixes.
Impacted environment parameters:
- TRADINGVIEW_HOST -> BINANCE_TRADINGVIEW_HOST
- TRADINGVIEW_PORT -> BINANCE_TRADINGVIEW_PORT
- TRADINGVIEW_LOG_LEVEL -> BINANCE_TRADINGVIEW_LOG_LEVEL
=> chore: change tradingview env param with prefix

CHANGELOG.md, public/css/App.css, public/js/SettingIcon.js
Added a button to clear selected symbols in Global Settings modal.
Why is this change required? What problem does it solve?
This is useful when users frequently experiment with different symbols and need to change the entire symbol list.
Now they can clear the symbol list with just one click instead of manually deselecting each symbol.
1. Add symbols to the list
2. Save changes
3. Use the "Clear selection" button
4. Save changes
5. Check if the list is empty
=> feat(SettingIcon): Add clear symbols button

CHANGELOG.md, public/js/CoinWrapperSetting.js
This PR highlights in the coin settings view which setting differs from the global configuration. 
This is done with a new function `warnIfAttributeCustomised` that changes the CSS after comparing the symbol attribute value (`this.props.symbolInfo.symbolConfiguration`) with the global attribute value (`this.props.configuration`).
This PR also adds the conservative mode setting in the settings view, since this has not been done in PR #585.
When playing with symbol settings, I often struggle to remember what I changed from the global settings and I end up going through a tedious comparison exercise. This feature helps identifying customised settings rapidly.
This is working on my prod setup.
=> feat: customised setting details

CHANGELOG.md, public/js/ProfitLossWrapper.js
A small UX improvement that makes the Closed Trades and Opened Trades accordions collapsable (same behaviour than the Account Balance accordion). On mobile, these accordions are collapsed by default.
The tooltip text of the Closed Trades header that was missing has been added.
This PR only impacts only `public/js/ProfitLossWrapper.js` file.
On mobile when you are trading multiple asset bases (USDT, ETH, BTC, BUSD...), these headers tend to be quite long forcing the user to scroll couple of times before reaching the symbol section.
This is working on my production setup.
=> feat: Collapsable ProfitLoss header

CHANGELOG.md, docker-compose.log.yml
To view the log, must access the server; the container outputs many logs. 
In addition, it is difficult to check later if any error occurs. 
To minimize system load, it's recommended to set `BINANCE_LOG_LEVEL` to `ERROR` in the `docker-compose.server.yml` or `docker-compose.yml` file. 
This will allow logging to `ERROR` messages only.
N/A
As description.
N/A
=> feat: added docker-compose.log.yml for log viewer

tradingview/main.py
Adding `/status` endpoint to TradingView for readness probe.
N/A
Preparing helm charts.
Yes.
```
/app # curl http://0.0.0.0:8082/status
{"status":"ok"}
```
=> feat: add status endpoint for tradingview
